### ISSUE TITLE
Restore responsive js and css to site

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/performant-web#5]
There are some css styles and javascript that have been removed from the home page template, because they were causing a "flash of unstyled content" bug. 

See [this template](https://github.com/performant-software/performant-web/blob/jf/makoto/_layouts/landing-page.html#L25-L27).

We want to restore those scripts, which load the responsive styles, so that it can be viewed more correctly on mobile devices. You can easily do that in your development environment, by removing the [liquid](https://shopify.github.io/liquid/) comments from before and after the scripts.html include:

```liquid
  {% comment  %} # <<  to see the page with the scripts loading, remove this
  {% include scripts.html %}
  {% endcomment %} # << and this
```
You should also see what I mean by the [flash of unstyled content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content). 

That is the bug to be fixed, so that the page loads cleanly, but also displays properly on mobile devices.

**Comment by mkobayashi21** [comment]
Where can I find the things that have been removed?

**Comment by jamiefolsom** [comment]
They're in the `_layouts` directory, in `default.html`, and `landing-page.html`. Here's the latter one: https://github.com/performant-software/performant-web/blob/jf/makoto/_layouts/landing-page.html#L25-L27 -- see some details above, too. Thx!

**Comment by mkobayashi21** [comment]
I do see the responsive behavior but not the fouc

**Comment by jamiefolsom** [comment]
I think you're right -- it's worse not to have the responsive styles, and the FOUC is very minimal. Why don't you open a pull request from your branch with the comments removed, and request a review from me?
