### ISSUE TITLE
Add Cookie Notification to site

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/performant-web#71]
- Should only require opt-in once.
- Use: http://localhost:3000/starter/notification.html

**Comment by cristyanc** [comment]
I'm not sure if you would like to implement this globally or only on the homepage. 
With the FRONT code, the concent message will appear everytime a user navigates to the website or refresh the site, it doesn't store the response unless we implement any of the following:
- Vendor cookie consent JS, e.g. https://cookieconsent.insites.com/ or https://www.cookiebot.com
- Hubspot cookie consent  (I'm not sure if your current subscription covers this. I don't have access to manage and test this feature with my current account privileges)

Any thoughts?

**Comment by jamiefolsom** [comment]
Use hubspot code:

```
<!-- Start of HubSpot Embed Code -->
<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/5083848.js"></script>
<!-- End of HubSpot Embed Code -->
```
